# This is a basic workflow to help you get started with Actions as it give the reuslt of low, medium and high vulnerabilities in your code. You can modify this workflow as per your needs.
# this workflow is weak as we only need to view high and critical vulnerabilities but here we are also getting low and medium vulnerabilities which is not required. So we will modify this workflow in next file.
name: CI

on: [push]

jobs:
 sast_scan:
   name: Run Bandit Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Set up Python
     uses: actions/setup-python@v5
     with:
       python-version: 3.13

   - name: Install Bandit
     run: pip install bandit

   - name: Run Bandit Scan
   # where bandit will scan ( . means in current folder )
     run: bandit -ll -ii -r . -f json -o bandit-report.json
     # upload the bandit-report.json file as an artifact to be used in the next steps
   - name: Upload Artifact
     uses: actions/upload-artifact@v3
     if: always()
     with:
      name: bandit-findings
      path: bandit-report.json
